# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52c0b1cf1cf7c71918a175d51df21f84f518e2af042c6120ef754cd9901a58df0d2a2003bf14355367999f7c342bb74af65e916a2a28555d9efb94be7d96314d

test:
  secret_key_base: 861bb405454e978301bf661ce2878d87e2d42fc7634bafc5df55e0eb96f0afc8a26b4ac1f55ae2c7878fac8b7754bfa2fea756f3d6b9ad158130b378eefb016f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
